window.__ModuleLoader__.load({
  id: '@dangosys/dsh-singularity/chat',
  factory: () => {
    const module = { exports: {} }
    const API = '/singular/chat'; const SEND = '/singular/message'; const STYLE_ID = 'dsh-chat-style'
    const CSS = `.canvas-chat{position:absolute;left:20px;bottom:20px;z-index:4;width:min(430px,calc(100% - 40px));box-sizing:border-box;padding:12px;border:1px solid #aebacc;border-radius:8px;background:#fffffff2;color:#172033;box-shadow:0 12px 28px #23304426;backdrop-filter:blur(10px)}.canvas-chat-anchor{position:absolute;right:-1px;top:50%;width:2px;height:2px}.canvas-chat-head{display:flex;align-items:center;justify-content:space-between;gap:12px;margin:0 0 8px;color:#52627a;font-size:12px;font-weight:650}.canvas-chat-target{min-width:0;overflow:hidden;color:#172033;font-size:13px;font-weight:700;text-overflow:ellipsis;white-space:nowrap}.canvas-chat-form,.chat-session-form{display:flex;align-items:flex-end;gap:8px}.canvas-chat textarea,.chat-session-form textarea{box-sizing:border-box;min-width:0;flex:1;resize:none;border:1px solid #aebacc;border-radius:6px;padding:9px 10px;background:#fff;color:#172033;font:13px system-ui;line-height:1.4}.canvas-chat textarea{height:50px}.canvas-chat textarea:disabled{background:#f1f5f9;color:#7a8799}.canvas-chat textarea::placeholder,.chat-session-form textarea::placeholder{color:#7a8799}.canvas-chat button,.chat-session-form button{width:34px;height:34px;flex:none;border:0;border-radius:6px;background:#35557d;color:#fff;cursor:pointer;font:18px system-ui}.canvas-chat button:disabled{background:#aebacc;cursor:default}.chat-session{display:flex;flex-direction:column;height:100%;min-height:0}.chat-session-log{min-height:0;flex:1;overflow:auto;padding:12px;background:#f8fafc}.chat-line{margin:0 0 8px;padding:9px 10px;border:1px solid #dbe3ed;border-radius:7px;background:#fff;color:#172033;white-space:pre-wrap;word-break:break-word;line-height:1.45}.chat-line[data-kind="agent"]{border-left:3px solid #35557d}.chat-session-form{padding:10px 12px;border-top:1px solid #d8e0ea;background:#fff}.chat-session-form textarea{height:48px}.chat-error{padding:7px 10px;color:#b42318;font-size:12px}`
    const h = (tag, props = {}, ...children) => { const node = document.createElement(tag); Object.entries(props).forEach(([key, value]) => { if (key === 'className') node.className = value; else if (key === 'dataset') Object.assign(node.dataset, value); else node.setAttribute(key, value) }); for (const child of children) if (child) node.append(child); return node }
    const text = value => document.createTextNode(String(value))
    const messageText = item => { const message = item.type === 'assistant/message' ? item.data.message : item.data; if (!Array.isArray(message.content)) throw new Error(`chat: message "${message.id}" has no content`); return message.content.map(block => block.type === 'text' ? block.text : JSON.stringify(block)).join('') }
    const targetId = target => target.group?.routerId ?? target.routerId ?? target.id
    const queryOf = target => target.group ? `group=${encodeURIComponent(target.group.id)}` : target.routerId ? `group=${encodeURIComponent(target.id)}` : `agent=${encodeURIComponent(target.id)}`
    const sessions = new Map(); let target; let dock; let dockTarget; let dockInput; let dockSend
    function line(item) { const row = h('div', { className: 'chat-line', dataset: { kind: item.type === 'assistant/message' ? 'agent' : 'human' } }); row.textContent = messageText(item); return row }
    async function send(target, input) { const value = input.value.trim(); if (!value) return; input.value = ''; const response = await fetch(SEND, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ to: targetId(target), content: [{ type: 'text', text: value }] }) }); if (!response.ok) throw new Error(await response.text()) }
    function updateDock() { dockTarget.textContent = target ? target.name ?? `Session ${target.id}` : 'Select an agent or group'; dockInput.disabled = !target; dockSend.disabled = !target; dockInput.placeholder = target ? `Message ${target.name ?? target.id}...` : 'Select an agent or group on the canvas' }
    function ensureDock() {
      if (dock) return
      const root = document.getElementById('canvas-root'); if (!root) throw new Error('chat: canvas is not open')
      dockTarget = h('div', { className: 'canvas-chat-target' }); const head = h('header', { className: 'canvas-chat-head' }, text('Send to'), dockTarget); dockInput = h('textarea', { rows: 2 }); dockSend = h('button', { type: 'submit', title: 'Send', 'aria-label': 'Send' }); dockSend.textContent = '↑'; const form = h('form', { className: 'canvas-chat-form' }, dockInput, dockSend); form.onsubmit = async event => { event.preventDefault(); await send(target, dockInput) }; dock = h('section', { className: 'canvas-chat' }, head, form, h('span', { className: 'canvas-chat-anchor' })); root.append(dock); updateDock()
    }
    function createSession(next) {
      const id = `${next.group ? 'group' : 'agent'}:${next.group?.id ?? next.id}`
      if (sessions.has(id)) return id
      const log = h('div', { className: 'chat-session-log' }); const input = h('textarea', { rows: 2, placeholder: `Message ${next.name ?? next.id}...` }); const submit = h('button', { type: 'submit', title: 'Send', 'aria-label': 'Send' }); submit.textContent = '↑'; const form = h('form', { className: 'chat-session-form' }, input, submit); const body = h('div', { className: 'chat-session' }, log, form); const record = { target: next, source: null, log, session: true }; form.onsubmit = async event => { event.preventDefault(); await send(next, input) }; document.dispatchEvent(new CustomEvent('sticky:open', { detail: { id, title: next.name ?? `Session ${next.id}`, body, target: next, session: true, dispose: () => record.source?.close() } })); record.source = new EventSource(`${API}?${queryOf(next)}`); record.source.addEventListener('message', frame => { const item = JSON.parse(frame.data); log.append(line(item)); log.scrollTop = log.scrollHeight }); record.source.onerror = () => { record.source.close(); record.source = null; log.append(h('div', { className: 'chat-error' }, text('chat stream closed'))) }; sessions.set(id, record); return id
    }
    function activate(next, id = createSession(next)) { ensureDock(); target = next; updateDock(); document.dispatchEvent(new CustomEvent('singularity:chat-target', { detail: { target: next, id: next.id, stickyId: id } })) }
    function agent(event) { activate(event.detail) }
    function group(event) { activate({ ...event.detail, group: event.detail }) }
    function sticky(event) { if (event.detail.target) activate(event.detail.target, event.detail.id) }
    function closed(event) { const record = sessions.get(event.detail.id); if (!record) return; record.source?.close(); sessions.delete(event.detail.id); if (event.detail.id === `${target?.group ? 'group' : 'agent'}:${target?.group?.id ?? target?.id}`) { target = undefined; updateDock(); document.dispatchEvent(new CustomEvent('singularity:chat-target', { detail: {} })) } }
    function canvasOpen() { ensureDock() }
    function canvasClosed() { for (const record of sessions.values()) record.source?.close(); sessions.clear(); target = undefined; dock?.remove(); dock = undefined; dockTarget = undefined; dockInput = undefined; dockSend = undefined }
    function apply(ctx) { ctx.effect(() => { const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = CSS; document.head.append(style); document.querySelectorAll('.canvas-chat').forEach(node => node.remove()); document.addEventListener('singularity:agent', agent); document.addEventListener('singularity:group', group); document.addEventListener('sticky:selected', sticky); document.addEventListener('sticky:closed', closed); document.addEventListener('canvas:open', canvasOpen); document.addEventListener('canvas:close', canvasClosed); return () => { document.removeEventListener('singularity:agent', agent); document.removeEventListener('singularity:group', group); document.removeEventListener('sticky:selected', sticky); document.removeEventListener('sticky:closed', closed); document.removeEventListener('canvas:open', canvasOpen); document.removeEventListener('canvas:close', canvasClosed); canvasClosed(); style.remove() } }, 'chat: lifecycle') }
    module.exports.apply = apply
    return module.exports
  },
})
