export const GRAPH_PATH = '/singularity/graph'
export const LAYOUT_PATH = '/singularity/layout'
export const EVENTS_PATH = '/singularity/events'
export const MAP_PATH = '/singularity/map'
export const GRAPHS_PATH = '/singularity/graphs'
export const GRAPH_ENVS_PATH = '/singularity/graph-envs'
export const REPO_CHECK_PATH = '/singularity/repo-check'
export const HITL_PATH = '/singularity/hitl'
