export const GRAPH_PATH = '/singularity/graph'
export const LAYOUT_PATH = '/singularity/layout'
export const EVENTS_PATH = '/singularity/events'
export const TRANSCRIPT_PATH = '/singularity/transcript'
export const NOTICES_PATH = '/singularity/notices'
