window.__ModuleLoader__.load({
  id: '@dangosys/dsh-singularity/node',
  factory: () => {
    const module = { exports: {} }
    const STYLE_ID = 'dsh-node-style'
    const CSS = ` .canvas-node{position:absolute;box-sizing:border-box;padding:15px 15px 13px;border:1px solid #46616a;border-radius:13px;background:linear-gradient(145deg,#1d2c33f2,#142127f2);color:#ecf5f1;cursor:pointer;box-shadow:0 14px 28px #050b0e66,0 1px 0 #ffffff0a inset;transition:transform .16s ease,box-shadow .16s ease,border-color .16s ease}.canvas-node:hover{border-color:#9be8c4;box-shadow:0 18px 34px #050b0e8c,0 0 0 4px #9be8c414,0 1px 0 #ffffff12 inset;transform:translateY(-2px)}.canvas-node[data-status="running"]{border-color:#68c69b}.canvas-node[data-status="failed"]{border-color:#b96f5d}.canvas-node[data-shape="circle"]{border-radius:50%;display:grid;place-items:center;text-align:center}.canvas-node[data-shape="diamond"]{transform:rotate(45deg);border-radius:8px}.canvas-node[data-shape="diamond"]>*{transform:rotate(-45deg)}.canvas-node[data-shape="diamond"]:hover{transform:rotate(45deg) translateY(-2px)}.canvas-node-name{padding-right:25px;color:#f3f8f5;font-size:13px;font-weight:700;letter-spacing:-.01em;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.canvas-node-meta{margin-top:10px;color:#91aaa8;font-size:11px;display:flex;align-items:center;justify-content:space-between;gap:12px;text-transform:uppercase;letter-spacing:.06em}.canvas-node-meta>span:last-child{color:#67817f;font-size:10px}.canvas-node-report{position:absolute;right:8px;top:8px;display:grid;place-items:center;width:22px;height:22px;border:1px solid transparent;border-radius:7px;background:transparent;color:#789492;cursor:pointer;font-size:13px}.canvas-node-report:hover{border-color:#507066;background:#29443b;color:#b8f5d2}.canvas-node-unread{position:absolute;right:9px;top:9px;width:8px;height:8px;border:2px solid #142127;border-radius:50%;background:#f5b762;display:none;box-shadow:0 0 12px #f5b76299}.canvas-node[data-unread="true"] .canvas-node-unread{display:block}.canvas-dot{width:7px;height:7px;border-radius:50%;display:inline-block;margin-right:6px;background:#718785;box-shadow:0 0 0 3px #71878518}.canvas-dot[data-status="running"]{background:#83e3b2;box-shadow:0 0 0 3px #83e3b21c,0 0 10px #83e3b288}.canvas-dot[data-status="done"]{background:#8ecbb0}.canvas-dot[data-status="failed"]{background:#f18469}.canvas-group{position:absolute;border:1px dashed #53706f;border-radius:17px;background:#1e373425;cursor:pointer;box-shadow:0 0 0 1px #9be8c408 inset}.canvas-group:hover{border-color:#83e3b2;background:#23423936}.canvas-group-label{position:absolute;top:-11px;left:15px;padding:3px 8px;border:1px solid #46616a;border-radius:6px;background:#142127;color:#9db6b1;font-size:10px;font-weight:700;letter-spacing:.1em;text-transform:uppercase}`
    const h = (tag, props = {}, ...children) => { const node = document.createElement(tag); Object.entries(props).forEach(([key, value]) => { if (key === 'className') node.className = value; else if (key === 'dataset') Object.assign(node.dataset, value); else node.setAttribute(key, value) }); for (const child of children) node.append(child); return node }
    const text = value => document.createTextNode(String(value))
    function draw(event) { const layer = document.querySelector('.canvas-nodes'); const groups = document.querySelector('.canvas-groups'); if (!layer || !groups) return; layer.replaceChildren(); groups.replaceChildren(); const snapshot = event.detail.snapshot; const byId = new Map(snapshot.agents.map(agent => [agent.id, agent])); snapshot.groups.forEach(group => { const members = group.memberIds.map(id => byId.get(id)); if (members.some(agent => !agent?.node)) throw new Error(`node: group "${group.id}" has agent without node`); const nodes = members.map(agent => agent.node); const x = Math.min(...nodes.map(node => node.x)) - 22; const y = Math.min(...nodes.map(node => node.y)) - 30; const width = Math.max(...nodes.map(node => node.x + node.width)) - x + 22; const height = Math.max(...nodes.map(node => node.y + node.height)) - y + 30; const box = h('div', { className: 'canvas-group', style: `left:${x}px;top:${y}px;width:${width}px;height:${height}px` }, h('div', { className: 'canvas-group-label' }, text(`Group ${group.id}`))); box.onclick = () => document.dispatchEvent(new CustomEvent('singularity:group', { detail: group })); groups.append(box) }); snapshot.agents.forEach(agent => { if (!agent.node) throw new Error(`node: agent "${agent.id}" has no canvas node`); const node = agent.node; const shape = node.shape; const item = h('article', { className: 'canvas-node', dataset: { agentId: agent.id, shape, status: agent.status, unread: 'false' }, style: `left:${node.x}px;top:${node.y}px;width:${node.width}px;height:${node.height}px` }, h('span', { className: 'canvas-node-unread' }), h('div', { className: 'canvas-node-name' }, text(agent.name)), h('div', { className: 'canvas-node-meta' }, h('span', {}, h('span', { className: 'canvas-dot', dataset: { status: agent.status } }), text(agent.status)), h('span', {}, text(agent.routerFor ? 'router' : 'agent')))); const report = h('button', { className: 'canvas-node-report', title: 'Open report', 'aria-label': 'Open report' }, text('↗')); report.onclick = event => { event.stopPropagation(); document.dispatchEvent(new CustomEvent('singularity:report', { detail: agent })) }; item.append(report); item.onclick = () => { document.dispatchEvent(new CustomEvent('singularity:unread', { detail: { agentId: agent.id, unread: false } })); document.dispatchEvent(new CustomEvent('singularity:agent', { detail: agent })) }; layer.append(item) }) }
    function unread(event) { const item = [...document.querySelectorAll('.canvas-node')].find(node => node.dataset.agentId === event.detail.agentId); if (item) item.dataset.unread = String(event.detail.unread) }
    function apply(ctx) { ctx.effect(() => { const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = CSS; document.head.append(style); document.addEventListener('canvas:graph', draw); document.addEventListener('singularity:unread', unread); return () => { document.removeEventListener('canvas:graph', draw); document.removeEventListener('singularity:unread', unread); style.remove() } }, 'node: lifecycle') }
    module.exports.apply = apply
    return module.exports
  },
})
