window.__ModuleLoader__.load({
  id: '@dangosys/dsh-singularity/node',
  factory: () => {
    const module = { exports: {} }
    const STYLE_ID = 'dsh-node-style'
    const CSS = `.canvas-node{position:absolute;box-sizing:border-box;padding:13px;border:1px solid #9aa8ba;background:#fff;color:#172033;cursor:pointer;box-shadow:0 4px 12px #2330441c;transition:box-shadow .15s,border-color .15s}.canvas-node:hover{border-color:#2563eb;box-shadow:0 7px 18px #2330442b}.canvas-node[data-shape="circle"]{border-radius:50%;display:grid;place-items:center;text-align:center}.canvas-node[data-shape="diamond"]{transform:rotate(45deg);border-radius:6px}.canvas-node[data-shape="diamond"]>*{transform:rotate(-45deg)}.canvas-node-name{font-weight:700;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.canvas-node-meta{margin-top:8px;color:#52627a;font-size:12px;display:flex;justify-content:space-between;gap:12px}.canvas-node-report{position:absolute;right:5px;top:5px;width:22px;height:22px;border:0;border-radius:5px;background:transparent;color:#40506a;cursor:pointer}.canvas-node-report:hover{background:#e8edf4}.canvas-node-unread{position:absolute;right:6px;top:6px;width:9px;height:9px;border-radius:50%;background:#dc2626;display:none;box-shadow:0 0 0 2px #fff}.canvas-node[data-unread="true"] .canvas-node-unread{display:block}.canvas-dot{width:8px;height:8px;border-radius:50%;display:inline-block;margin-right:5px;background:#8b96a5}.canvas-dot[data-status="running"]{background:#2563eb}.canvas-dot[data-status="done"]{background:#16834b}.canvas-dot[data-status="failed"]{background:#dc2626}.canvas-group{position:absolute;border:1px solid #8796aa;background:#dce4efcc;border-radius:8px;cursor:pointer}.canvas-group-label{position:absolute;top:7px;left:10px;color:#334155;font-size:12px;font-weight:700}`
    const h = (tag, props = {}, ...children) => { const node = document.createElement(tag); Object.entries(props).forEach(([key, value]) => { if (key === 'className') node.className = value; else if (key === 'dataset') Object.assign(node.dataset, value); else node.setAttribute(key, value) }); for (const child of children) node.append(child); return node }
    const text = value => document.createTextNode(String(value))
    function draw(event) { const layer = document.querySelector('.canvas-nodes'); const groups = document.querySelector('.canvas-groups'); if (!layer || !groups) return; layer.replaceChildren(); groups.replaceChildren(); const snapshot = event.detail.snapshot; const byId = new Map(snapshot.agents.map(agent => [agent.id, agent])); snapshot.groups.forEach(group => { const members = group.memberIds.map(id => byId.get(id)); if (members.some(agent => !agent?.node)) throw new Error(`node: group "${group.id}" has agent without node`); const nodes = members.map(agent => agent.node); const x = Math.min(...nodes.map(node => node.x)) - 22; const y = Math.min(...nodes.map(node => node.y)) - 30; const width = Math.max(...nodes.map(node => node.x + node.width)) - x + 22; const height = Math.max(...nodes.map(node => node.y + node.height)) - y + 30; const box = h('div', { className: 'canvas-group', style: `left:${x}px;top:${y}px;width:${width}px;height:${height}px` }, h('div', { className: 'canvas-group-label' }, text(`Group ${group.id}`))); box.onclick = () => document.dispatchEvent(new CustomEvent('singularity:group', { detail: group })); groups.append(box) }); snapshot.agents.forEach(agent => { if (!agent.node) throw new Error(`node: agent "${agent.id}" has no canvas node`); const node = agent.node; const shape = node.shape; const item = h('article', { className: 'canvas-node', dataset: { agentId: agent.id, shape, unread: 'false' }, style: `left:${node.x}px;top:${node.y}px;width:${node.width}px;height:${node.height}px` }, h('span', { className: 'canvas-node-unread' }), h('div', { className: 'canvas-node-name' }, text(agent.name)), h('div', { className: 'canvas-node-meta' }, h('span', {}, h('span', { className: 'canvas-dot', dataset: { status: agent.status } }), text(agent.status)), h('span', {}, text(agent.routerFor ? 'router' : 'agent')))); const report = h('button', { className: 'canvas-node-report', title: 'Open report', 'aria-label': 'Open report' }, text('i')); report.onclick = event => { event.stopPropagation(); document.dispatchEvent(new CustomEvent('singularity:report', { detail: agent })) }; item.append(report); item.onclick = () => { document.dispatchEvent(new CustomEvent('singularity:unread', { detail: { agentId: agent.id, unread: false } })); document.dispatchEvent(new CustomEvent('singularity:agent', { detail: agent })) }; layer.append(item) }) }
    function unread(event) { const item = [...document.querySelectorAll('.canvas-node')].find(node => node.dataset.agentId === event.detail.agentId); if (item) item.dataset.unread = String(event.detail.unread) }
    function apply(ctx) { ctx.effect(() => { const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = CSS; document.head.append(style); document.addEventListener('canvas:graph', draw); document.addEventListener('singularity:unread', unread); return () => { document.removeEventListener('canvas:graph', draw); document.removeEventListener('singularity:unread', unread); style.remove() } }, 'node: lifecycle') }
    module.exports.apply = apply
    return module.exports
  },
})
