window.__ModuleLoader__.load({
  id: '@dangosys/dsh-singularity/node',
  factory: () => {
    const module = { exports: {} }
    const STYLE_ID = 'dsh-node-style'
    const CSS = `.canvas-node{position:absolute;z-index:2;box-sizing:border-box;width:160px;height:50px;padding:10px 11px;border:1px solid #242728;border-radius:14px;background:#0E1116;color:#d9dde5;cursor:pointer;box-shadow:0 8px 24px rgba(0,0,0,.34);transition:border-color .15s,box-shadow .15s}.canvas-node[data-selected="true"]{border-color:#4DA3FF;box-shadow:0 0 0 1px rgba(77,163,255,.22),0 10px 28px rgba(0,0,0,.48)}.canvas-node:hover{border-color:#38516d;box-shadow:0 10px 28px rgba(0,0,0,.48);transform:translateY(-1px)}.canvas-node[data-status="running"]{border-color:#385f87}.canvas-node[data-status="failed"]{border-color:#713d43}.canvas-node[data-selected="true"]{border-color:#4DA3FF;box-shadow:0 0 0 1px rgba(77,163,255,.22),0 10px 28px rgba(0,0,0,.48)}.canvas-node-name{font-weight:700;line-height:15px;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.canvas-node-meta{margin-top:4px;color:#656e7b;font-size:10px;display:flex;justify-content:space-between;gap:12px}.canvas-node-report{position:absolute;right:5px;top:5px;width:18px;height:18px;border:0;border-radius:4px;background:transparent;color:#697483;cursor:pointer}.canvas-node-report:hover{background:#1a1e24;color:#d9dde5}.canvas-node-unread{position:absolute;right:6px;top:6px;width:6px;height:6px;border-radius:50%;background:#ff5d63;display:none;box-shadow:0 0 0 2px #0E1116}.canvas-node[data-unread="true"] .canvas-node-unread{display:block}.canvas-dot{width:6px;height:6px;border-radius:50%;display:inline-block;margin-right:5px;background:#6B7280}.canvas-dot[data-status="idle"]{background:#6B7280}.canvas-dot[data-status="waiting"]{background:#E8B84A}.canvas-dot[data-status="active"]{background:#3DFF8A}.canvas-dot[data-status="running"]{background:#4DA3FF}.canvas-dot[data-status="running"]{background:#4DA3FF}.canvas-dot[data-status="done"]{background:#3DFF8A}.canvas-dot[data-status="failed"]{background:#ff5d63}.canvas-dot[data-status="waiting"]{background:#E8B84A}.canvas-dot[data-status="idle"]{background:#6B7280}.canvas-group{position:absolute;z-index:1;border:1px solid #242728;background:#0E111688;border-radius:14px;cursor:pointer}.canvas-group-label{position:absolute;top:8px;left:10px;color:#626b79;font-size:10px;font-weight:700}.canvas-inspector{position:absolute;z-index:4;right:19px;top:19px;width:224px;box-sizing:border-box;padding:12px;border:1px solid #242728;border-radius:14px;background:#0E1116;color:#d9dde5;box-shadow:0 10px 28px rgba(0,0,0,.42)}.canvas-inspector-title{font-weight:700;font-size:12px}.canvas-inspector-subtitle{margin-top:6px;color:#656e7b;font-size:10px}.canvas-inspector-callout{margin-top:10px;padding:9px;border:1px solid #242728;border-radius:8px;color:#d0d6df;font-size:10px;line-height:14px}.canvas-inspector-callout small{display:block;margin-top:3px;color:#656e7b}`
    const h = (tag, props = {}, ...children) => { const node = document.createElement(tag); Object.entries(props).forEach(([key, value]) => { if (key === 'className') node.className = value; else if (key === 'dataset') Object.assign(node.dataset, value); else node.setAttribute(key, value) }); for (const child of children) node.append(child); return node }
    const text = value => document.createTextNode(String(value))
    function layout(snapshot, origin) {
      if (!origin || !Number.isFinite(origin.x) || !Number.isFinite(origin.y)) throw new Error("node: graph origin is invalid")
      const roots = new Set(snapshot.roots); const agents = [...snapshot.agents].sort((a, b) => Number(roots.has(b.id)) - Number(roots.has(a.id))); const radius = Math.min(250, Math.max(170, Math.min(origin.x, origin.y) * .58)); const result = new Map()
      agents.forEach((agent, index) => { const angle = index === 0 ? -Math.PI / 2 : -Math.PI / 2 + (index % 2 === 1 ? -1 : 1) * Math.ceil(index / 2) * Math.PI / 3; result.set(agent.id, { x: origin.x + Math.cos(angle) * radius - 80, y: origin.y + Math.sin(angle) * radius - 25, width: 160, height: 50 }) })
      return result
    }
    function inspector(root, agent) {
      root.querySelector(".canvas-inspector")?.remove(); if (!agent) return
      root.append(h("aside", { className: "canvas-inspector" }, h("div", { className: "canvas-inspector-title" }, text(agent.name)), h("div", { className: "canvas-inspector-subtitle" }, text("spawned from singularity · " + agent.status)), h("div", { className: "canvas-inspector-callout" }, text("Planning next hop"), h("small", {}, text("Edges grow from the origin as agents spawn.")))))
    }
    function draw(event) {
      const layer = document.querySelector(".canvas-nodes"); const groups = document.querySelector(".canvas-groups"); const root = document.querySelector(".canvas-root"); if (!layer || !groups || !root) throw new Error("node: canvas layers are not mounted")
      const snapshot = event.detail.snapshot; const positions = layout(snapshot, event.detail.origin); layer.replaceChildren(); groups.replaceChildren(); const byId = new Map(snapshot.agents.map(agent => [agent.id, agent]))
      snapshot.groups.forEach(group => { const members = group.memberIds.map(id => byId.get(id)); if (members.some(agent => !agent)) throw new Error("node: group " + group.id + " references an unknown agent"); const nodes = members.map(agent => positions.get(agent.id)); if (nodes.some(item => !item)) throw new Error("node: group " + group.id + " has no visual position"); const x = Math.min(...nodes.map(item => item.x)) - 22; const y = Math.min(...nodes.map(item => item.y)) - 30; const width = Math.max(...nodes.map(item => item.x + item.width)) - x + 22; const height = Math.max(...nodes.map(item => item.y + item.height)) - y + 30; const box = h("div", { className: "canvas-group", style: "left:" + x + "px;top:" + y + "px;width:" + width + "px;height:" + height + "px" }, h("div", { className: "canvas-group-label" }, text("Group " + group.id))); box.onclick = () => document.dispatchEvent(new CustomEvent("singularity:group", { detail: group })); groups.append(box) })
      snapshot.agents.forEach(agent => { const position = positions.get(agent.id); if (!position) throw new Error("node: agent " + agent.id + " has no visual position"); const item = h("article", { className: "canvas-node", dataset: { agentId: agent.id, shape: "card", status: agent.status, selected: String(agent.id === (snapshot.roots[0] ?? snapshot.agents[0]?.id)), unread: "false" }, style: "left:" + position.x + "px;top:" + position.y + "px;width:" + position.width + "px;height:" + position.height + "px" }, h("span", { className: "canvas-node-unread" }), h("div", { className: "canvas-node-name" }, text(agent.name)), h("div", { className: "canvas-node-meta" }, h("span", {}, h("span", { className: "canvas-dot", dataset: { status: agent.status } }), text(agent.status)), h("span", {}, text(agent.routerFor ? "router" : "agent")))); const report = h("button", { className: "canvas-node-report", title: "Open report", "aria-label": "Open report" }, text("i")); report.onclick = event => { event.stopPropagation(); document.dispatchEvent(new CustomEvent("singularity:report", { detail: agent })) }; item.onclick = () => { layer.querySelectorAll(".canvas-node").forEach(node => { node.dataset.selected = "false" }); item.dataset.selected = "true"; document.dispatchEvent(new CustomEvent("singularity:unread", { detail: { agentId: agent.id, unread: false } })); document.dispatchEvent(new CustomEvent("singularity:agent", { detail: agent })); inspector(root, agent) }; layer.append(item) })
      inspector(root, snapshot.agents[0])
    }
    function unread(event) { const item = [...document.querySelectorAll('.canvas-node')].find(node => node.dataset.agentId === event.detail.agentId); if (item) item.dataset.unread = String(event.detail.unread) }
    function apply(ctx) { ctx.effect(() => { const style = document.createElement('style'); style.id = STYLE_ID; style.textContent = CSS; document.head.append(style); document.addEventListener('canvas:graph', draw); document.addEventListener('singularity:unread', unread); return () => { document.removeEventListener('canvas:graph', draw); document.removeEventListener('singularity:unread', unread); style.remove() } }, 'node: lifecycle') }
    module.exports.apply = apply
    return module.exports
  },
})
